export enum EventTypeEnum {
  CULT = "CULT",
  PRAYER = "PRAYER",
  BIBLE_STUDY = "BIBLE_STUDY",
  DISCIPLESHIP = "DISCIPLESHIP",
  TRAINING = "TRAINING",
  CONFERENCE = "CONFERENCE",
  RETREAT = "RETREAT",
  CELL_GROUP = "CELL_GROUP",
  OUTREACH = "OUTREACH",
  LEADER_MEETING = "LEADER_MEETING",
  MINISTRY_MEETING = "MINISTRY_MEETING",
  ASSEMBLY = "ASSEMBLY",
}
